config/routes.rb
  resources :downloads, only: :show

  # ResourceSync routes
  get '/.well-known/resourcesync' => 'resource_sync#source_description', as: :source_description
  get '/capabilitylist' => 'resource_sync#capability_list', as: :capability_list
  get '/resourcelist' => 'resource_sync#resource_list', as: :resource_list
  get '/changelist' => 'resource_sync#change_list', as: :change_list

  delete '/uploads/:id', to: 'uploads#destroy', as: :uploaded_file
  post '/uploads', to: 'uploads#create'
  # This is a hack that is required because the rails form the uploader is on
  # sets the _method parameter to patch when the work already exists.
  # Eventually it would be good to update the javascript so that it doesn't
  # submit the form, just the file and always uses POST.
  patch '/uploads', to: 'uploads#create'

  match 'batch_edits/clear' => 'batch_edits#clear', as: :batch_edits_clear, via: [:get, :post]
  resources :batch_edits, only: [:index] do
    member do
      delete :destroy
    end
    collection do
      get :index
      get :edit
      put :update
      delete :clear
      put :state
      put :all
    end
  end
  match 'batch_edits/:id' => 'batch_edits#add', :via => :put
  match 'batch_edits' => 'batch_edits#destroy_collection', :via => :delete

  resources :batch_uploads, only: [:new, :create], controller: 'batch_uploads'

  resources :collections, only: :show do # public landing show page
    member do
      get 'page/:page', action: :index
      get 'facet/:id', action: :facet, as: :dashboard_facet
      get :files
    end
  end

  # File Set routes
  scope :concern do
    resources :file_sets, only: [] do
      resource :fixity_checks, only: [:create]
      member do
        get 'stats'
      end
    end
  end

  resources :files, only: [] do
    member do
      get :citation, controller: :citations, action: :file, as: :citations
      get :stats, controller: :stats, action: :file, as: :stats
    end
  end

  # Generic work routes
  resources :works, only: [] do
    member do
      resources :transfers, as: :work_transfers, only: [:new, :create]
      resource :featured_work, only: [:create, :destroy]
      get :citation, controller: :citations, action: :work, as: :citations
      get :stats, controller: :stats, action: :work, as: :stats
      post 'trophy' => 'trophies#toggle_trophy' # used by hyrax/trophy.js
    end
  end

  # Depositors routes for proxy deposit
  post 'users/:user_id/depositors' => 'depositors#create', as: 'user_depositors'
  delete 'users/:user_id/depositors/:id' => 'depositors#destroy', as: 'user_depositor'
  get 'proxies' => 'depositors#index', as: 'depositors'

  resources :featured_work_lists, path: 'featured_works', only: :create

  resources :user_pinned_collections, only: [:create, :destroy]

  # Messages
  resources :notifications, only: [:destroy, :index] do
    collection do
      delete 'delete_all'
    end
  end
  if Hyrax.config.realtime_notifications?
    namespace :notifications do
      # WebSocket for notifications
      mount ActionCable.server => 'endpoint', as: :endpoint
    end
  end

  # User profile
  resources :users, only: [:index, :show] do
    resources :operations, only: [:index, :show], controller: 'operations'
  end

  # Dashboard page
  resource :dashboard, controller: 'dashboard', only: [:show]
  resources :dashboard, only: [] do
    collection do
      get 'activity', action: :activity, as: :dashboard_activity
      resources :transfers, only: [:index, :destroy] do
        member do
          put 'accept'
          put 'reject'
        end
      end
    end
  end

  namespace :dashboard do
    resources :works, only: :index
    get 'works/facet/:id',  controller: 'works', action: :facet, as: 'works_facet'
    resources :collections do # Dashboard -> All Collections and CRUD
      member do
        get 'page/:page', action: :index
        get 'facet/:id', action: :facet, as: :dashboard_facet
        get :files
      end
      collection do
        put '', action: :update
        put :remove_member
      end
    end
    post 'collections/:id', controller: 'collection_members', action: :update_members
    post 'collections/:child_id/within', controller: 'nest_collections', action: 'create_relationship_within', as: 'create_nest_collection_within'
    get 'collections/:parent_id/under', controller: 'nest_collections', action: 'create_collection_under', as: 'create_subcollection_under'
    post 'collections/:parent_id/under', controller: 'nest_collections', action: 'create_relationship_under', as: 'create_nest_collection_under'
    post 'collections/:child_id/remove_parent/:parent_id', controller: 'nest_collections', action: 'remove_relationship_above', as: 'remove_parent_relationship_above'
    post 'collections/:parent_id/remove_child/:child_id', controller: 'nest_collections', action: 'remove_relationship_under', as: 'remove_child_relationship_under'
    resources :profiles, only: [:show, :edit, :update]
  end

  # Routes for user's works, collections, highlights and shares
  # Preserves existing behavior by maintaining paths to /dashboard
  # Routes actions to the various My controllers
  scope :dashboard do
    namespace :my do
      resources :works, only: :index
      get '/works/page/:page', controller: 'works', action: :index
      get 'works/facet/:id', controller: 'works', action: :facet, as: 'dashboard_works_facet'
      resources :collections, only: :index # Dashboard -> My Collections only
      get '/collections/page/:page',  controller: 'collections', action: :index
      get '/collections/facet/:id',   controller: 'my/collections', action: :facet, as: 'dashboard_collections_facet'
    end

    get '/highlights',            controller: 'my/highlights', action: :index, as: 'dashboard_highlights'
    get '/highlights/page/:page', controller: 'my/highlights', action: :index
    get '/highlights/facet/:id',  controller: 'my/highlights', action: :facet, as: 'dashboard_highlights_facet'

    get '/shares',            controller: 'my/shares', action: :index, as: 'dashboard_shares'
    get '/shares/page/:page', controller: 'my/shares', action: :index
    get '/shares/facet/:id',  controller: 'my/shares', action: :facet, as: 'dashboard_shares_facet'
    scope :collections do
      get '/permission_template/new' => 'admin/permission_templates#new', as: :new_dashboard_collection_permission_template
      get '/:collection_id/permission_template/edit' => 'admin/permission_templates#edit', as: :edit_dashboard_collection_permission_template
      get '/:collection_id/permission_template' => 'admin/permission_templates#show', as: :dashboard_collection_permission_template
      patch '/:collection_id/permission_template' => 'admin/permission_templates#update'
      put '/:collection_id/permission_template' => 'admin/permission_templates#update'
      delete '/:collection_id/permission_template' => 'admin/permission_templates#destroy'
      post '/:collection_id/permission_template' => 'admin/permission_templates#create'
    end
  end

  # Contact form routes
  post 'contact' => 'contact_form#create', as: :contact_form_index
  get 'contact' => 'contact_form#new'

  get 'single_use_link/show/:id' => 'single_use_links_viewer#show', as: :show_single_use_link
  get 'single_use_link/download/:id' => 'single_use_links_viewer#download', as: :download_single_use_link
  post 'single_use_link/generate_download/:id' => 'single_use_links#create_download', as: :generate_download_single_use_link
  post 'single_use_link/generate_show/:id' => 'single_use_links#create_show', as: :generate_show_single_use_link
  get 'single_use_link/generated/:id' => 'single_use_links#index', as: :generated_single_use_links
  delete 'single_use_link/:id/delete/:link_id' => 'single_use_links#destroy', as: :delete_single_use_link

  resources :embargoes, controller: 'embargoes', only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  resources :leases, controller: 'leases', only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  # Permissions routes
  scope :concern do
    resources :permissions, only: [] do
      member do
        get :confirm
        post :copy
        get :confirm_access
        post :copy_access
      end
    end
  end

  # API routes
  if Hyrax.config.arkivo_api?
    namespace :api do
      if defined?(Hyrax::ArkivoConstraint)
        constraints Hyrax::ArkivoConstraint do
          resources :items, except: [:index, :edit, :new], defaults: { format: :json }
        end
      end

      get 'zotero' => 'zotero#initiate', as: :zotero_initiate
      get 'zotero/callback' => 'zotero#callback', as: :zotero_callback
    end
  end

  namespace :admin do
    namespace :analytics do
      resources :collection_reports, only: [:index, :show]
      resources :work_reports, only: [:index, :show]
    end
    resources :admin_sets do
      member do
        get :files
      end
      resource :permission_template
    end
    resources :users, only: [:index]
    resources :permission_template_accesses, only: :destroy
    resource 'stats', only: [:show]
    resources :features, only: [:index] do
      resources :strategies, only: [:update, :destroy]
    end
    resources :workflows
    resources :workflow_roles
    resource :appearance
    resources :collection_types, except: :show
    resources :collection_type_participants, only: [:create, :destroy]
  end

  resources :content_blocks, only: [] do
    member do
      patch :update
    end
    collection do
      get :edit
    end
  end
  resources :pages, only: [] do
    member do
      patch :update
    end
    collection do
      get :edit
    end
  end
  get 'about' => 'pages#show', key: 'about'
  get 'help' => 'pages#show', key: 'help'
  get 'terms' => 'pages#show', key: 'terms'
  get 'agreement' => 'pages#show', key: 'agreement'

  # Static page routes
  %w[zotero mendeley].each do |action|
    get action, controller: 'static', action: action, as: action
  end

app/controllers/hyrax/admin/analytics/analytics_controller.rb
# frozen_string_literal: true
module Hyrax
  module Admin
    module Analytics
      class AnalyticsController < ApplicationController
        include Hyrax::SingularSubresourceController
        before_action :set_months
        before_action :set_date_range
        before_action :set_document, only: [:show]
        with_themed_layout 'dashboard'

        def set_document
          @document = ::SolrDocument.find(params[:id])
        end

        def set_months
          @month_names = 12.downto(1).map { |n| DateTime::ABBR_MONTHNAMES.drop(1)[(Time.zone.today.month - n) % 12] }.reverse
        end

        def set_date_range
          @start_date = params[:start_date] || Hyrax.config.analytics_start_date
          @end_date = params[:end_date] || Time.zone.today + 1.day
        end

        def date_range
          "#{@start_date},#{@end_date}"
        end

        def paginate(results_array, rows: 10)
          return if results_array.nil?

          total_pages = (results_array.size.to_f / rows.to_f).ceil
          page = request.params[:page].nil? ? 1 : request.params[:page].to_i
          current_page = page > total_pages ? total_pages : page
          Kaminari.paginate_array(results_array, total_count: results_array.size).page(current_page).per(rows)
        end
      end
    end
  end
end

app/controllers/hyrax/admin/analytics/collection_reports_controller.rb
# frozen_string_literal: true
module Hyrax
  module Admin
    module Analytics
      class CollectionReportsController < AnalyticsController
        include Hyrax::BreadcrumbsForCollectionAnalytics
        def index
          return unless Hyrax.config.analytics == true

          @pageviews = Hyrax::Analytics.daily_events('collection-page-view')
          @work_page_views = Hyrax::Analytics.daily_events('work-in-collection-view')
          @downloads = Hyrax::Analytics.daily_events('work-in-collection-download')
          @all_top_collections = Hyrax::Analytics.top_events('work-in-collection-view', date_range)
          @top_collections = paginate(@all_top_collections, rows: 10)
          @top_downloads = Hyrax::Analytics.top_events('work-in-collection-download', date_range)
          @top_collection_pages = Hyrax::Analytics.top_events('collection-page-view', date_range)
          respond_to do |format|
            format.html
            format.csv { export_data }
          end
        end

        def show
          @document = ::SolrDocument.find(params[:id])
          return unless Hyrax.config.analytics == true
          # @path = request.base_url + @path if Hyrax.config.analytics_provider == 'matomo'
          @pageviews = Hyrax::Analytics.daily_events_for_id(@document.id, 'collection-page-view')
          @work_page_views = Hyrax::Analytics.daily_events_for_id(@document.id, 'work-in-collection-view')
          @uniques = Hyrax::Analytics.unique_visitors_for_id(@document.id)
          @downloads = Hyrax::Analytics.daily_events_for_id(@document.id, 'work-in-collection-download')
          respond_to do |format|
            format.html
            format.csv { export_data }
          end
        end

       private

        # rubocop:disable Metrics/MethodLength
        def export_data
          csv_row = CSV.generate do |csv|
            csv << ["Name", "ID", "View of Works In Collection", "Downloads of Works In Collection", "Collection Page Views"]
            @all_top_collections.each do |collection|
              document = begin
                           ::SolrDocument.find(collection[0])
                         rescue
                           "Collection deleted"
                         end
              download_match = @top_downloads.detect { |a, _b| a == collection[0] }
              download_count = download_match ? download_match[1] : 0
              collection_match = @top_collection_pages.detect { |a, _b| a == collection[0] }
              collection_count = collection_match ? collection_match[1] : 0
              csv << [document, collection[0], collection[1], download_count, collection_count]
            end
          end
          send_data csv_row, filename: "#{@start_date}-#{@end_date}-collections.csv"
        end
        # rubocop:enable Metrics/MethodLength
      end
    end
  end
end

app/views/hyrax/admin/analytics/work_reports/_custom_range.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h4><%= t('.summary_heading') %></h4></div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th><%= @start_date.to_date.strftime("%B %d, %Y") %> through <%= @end_date.to_date.strftime("%B %d, %Y") %></th>
        </tr>
      </thead>
      <tbody>
        <% if @pageviews %>
          <tr>
            <td><b><%= t('.page_views') %></b></td>
            <td><%= @pageviews.range(@start_date.to_date, @end_date.to_date) %></td>
          </tr>
        <% end %>
        <% if @downloads %>
          <tr>
            <td><b><%= t('.file_downloads') %></b></td>
            <td><%= @downloads.range(@start_date.to_date, @end_date.to_date) %></td>
          </tr>
        <% end %>
        <% if @uniques %>
          <tr>
            <td><b><%= t('.unique_visitors') %></b></td>
            <td><%= @uniques.range(@start_date.to_date, @end_date.to_date) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if params[:start_date] %>
  <% if @top_works %>
      <div><%= render 'top_works' %></div>
  <% end %>

  <% if @top_file_set_downloads %>
    <div><%= render 'top_file_set_downloads' %></div>
  <% end %>
<% end %>

app/views/hyrax/admin/analytics/work_reports/_monthly_summary.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t('.monthly_subtitle') %> <%= Time.zone.today.strftime("%B %Y") %></h4>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>&nbsp;</th>
        <% @month_names.each do |name| %>
          <th><%= name %></th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% if @pageviews %>    
        <tr>
          <td><b><%= t('.page_views') %></b></td>
          <% @month_names.each do |name| %>
            <td><%= @pageviews.month(name.to_date) %></td>
          <% end %>
        </tr>
      <% end %>
      <% if @downloads %>
        <tr>
          <td><b><%= t('.file_downloads') %></b></td>
            <% @month_names.each do |name| %>
            <td><%= @downloads.month(name.to_date) %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/hyrax/admin/analytics/work_reports/_summary.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t('.subtitle') %></h4>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th><%= t('.today') %></th>
          <th><%= t('.this_week') %></th>
          <th><%= t('.this_month') %></th>
          <th><%= t('.this_year') %></th>
          <th><%= t('.all_time') %></th>
        </tr>
      </thead>
      <tbody>
        <% if @pageviews %>
          <tr>
            <td><b><%= t('.page_views') %></b></td>
            <td><%= @pageviews.day %></td>
            <td><%= @pageviews.week %></td>
            <td><%= @pageviews.month %></td>
            <td><%= @pageviews.year %></td>
            <td><%= @pageviews.all %></td>
          </tr>
        <% end %>
        <% if @downloads %>
          <tr>
            <td><b><%= t('.file_downloads') %></b></td>
            <td><%= @downloads.day %></td>
            <td><%= @downloads.week %></td>
            <td><%= @downloads.month %></td>
            <td><%= @downloads.year %></td>
            <td><%= @downloads.all %></td>
          </tr>
        <% end %>
        <% if @uniques %>
          <tr>
            <td><b><%= t('.unique_visitors') %></b></td>
            <td><%= @uniques.day %></td>
            <td><%= @uniques.week %></td>
            <td><%= @uniques.month %></td>
            <td><%= @uniques.year %></td>
            <td><%= @uniques.all %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

 <% if @top_works %>
    <div><%= render 'top_works' %></div>
<% end %>

<% if @top_file_set_downloads %>
  <div><%= render 'top_file_set_downloads' %></div>
<% end %>

app/views/hyrax/admin/analytics/work_reports/_top_file_set_downloads.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t('.top_downloads')%></h4>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= t('.file_name')%></th>
        <th><%= t('.file') %> ID</th>
        <th><%= t('.file_downloads')%></th>
      </tr>
      </thead>
      <tbody>
          <% @top_file_set_downloads.each do |download| %>
            <tr>
              <td><%= download[1] %></td> 
              <td><%= download[0] %></td>  
              <td><%= download[2] %></td>
            </tr>
          <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer">
    <div class="pull-right">
     <%= paginate @top_file_set_downloads %> 
    </div>
  </div>
</div>
 

app/views/hyrax/admin/analytics/work_reports/_top_works.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
   <h4><%= t('.top_works') %>
      <div class="btn-group pull-right">
        <%= link_to "#{t('.export')}", admin_analytics_work_reports_path(start_date: @start_date, end_date: @end_date, format: :csv, disposition: "attachment"), class: "btn btn-default" %>
      </div>
  </h4>
  </div>

  <div class="panel-body">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t('.work_title')%></th>
          <th>ID</th>
          <th><%= t('.work_views')%></th>
          <th><%= t('.file_downloads')%></th>
        </tr>
      </thead>
      <tbody>
        <% @top_works.each do |work| %>
            <tr>
              <td><%= link_to work[1], admin_analytics_work_report_path(work[0]) %></td>
              <td><%= work[0] %></td>
              <td><%= work[2] %></td>
              <td><%= work[3] %></td>
            </tr>       
        <% end %>
      </tbody>
    </table>
  </div>
  

  <div class="panel-footer">
    <div class="pull-right">
      <%= paginate @top_works %>
    </div>
  </div>

</div>

app/views/hyrax/admin/analytics/work_reports/_work_counts.html.erb
<div class="row">
  <div class="col-xs-12 work-counts">
    <div class="work-count-border col-sm-2 col-sm-offset-3 pull-left text-center">
       <% @file_sizes_total_bytes = @file_sizes.inject(0, :+) %>
       <% @file_size_total = (@file_sizes_total_bytes / 1.0.megabyte).round(2) %>
      <h4 class="work-count-title"><%= @file_size_total %>MB</p>
      <p>total size</p>
    </div>
    <div class="work-count-border col-sm-2 pull-left text-center">
      <h4 class="work-count-title"></p>
      <p>child works</p>
    </div>
    <div class="work-count-border col-sm-2 pull-left text-center">
      <h4 class="work-count-title"><%= @files.count %></p>
      <p>files</p>
    </div>
  </div>
</div>

app/views/hyrax/admin/analytics/work_reports/_work_files.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4><%= t('.title') %></h4>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>&nbsp;</th>
        <th></th>
        <th><%= t('.total_downloads') %> (YTD)</th>
      </tr>
      </thead>
      <tbody>

      <% @files.each do |file| %>
        <% @file_sizes = [] %>
        <% f = SolrDocument.find(file) %>
        <% if f %>
          <% @file_sizes.push(f.file_size) %>
          <tr>
            <td><%= f %></td>
            <td><%= f.id %></td>
            <td><%= Hyrax::Analytics.daily_events_for_id(@document.id, 'file_set_in_work_download').all %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer">
    <div class="pull-right">
     <%= paginate @files %> 
    </div>
  </div>
</div>

app/views/hyrax/admin/analytics/work_reports/index.html.erb
<% provide :page_title, "#{t('.title')}" %>

<% provide :page_header do %>
  <h1><span class="fa fa-bar-chart" aria-hidden="true"></span><%= t('.title') %></h1>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <div class="work-reports">

    <div class="panel panel-default">
    <% if Hyrax.config.analytics == true %>
      <% if current_user.ability.admin? %>
        <div class="panel-heading"><b><%= @works_count %> <%= t('.works') %></b> <%= t('.repo_summary') %> <b><%= @pageviews.all if @pageviews %> <%= t('.views') %></b> <%= t('.and') %> <b><%= @downloads.all if @downloads %> <%= t('.downloads') %></b>.</div>
      <% else %>
        <div class="panel-heading"><%= t('.access_to') %> <b><%= @works_count %> <%= t('.works') %></b>.</div>
      <% end %>
        <div class="panel-body">
              <% if current_user.ability.admin? %>
              <div class="row text-center">
                <div class="nav nav-pills btn-group" role="group">
                    <% if params[:start_date] %>
                     <a button id='summary-btn' class="btn btn-default nav-link" type="button" href="#summary" data-toggle="pill">
                    <% else %>
                     <a button id='summary-btn' class="btn btn-primary nav-link" type="button" href="#summary" data-toggle="pill">
                    <% end %>
                        <%= t('.summary') %>
                     </a>
                      <a button id='monthly-btn' class="btn btn-default nav-link" type="button" href="#monthly" data-toggle="pill">
                        <%= t('.monthly') %>
                      </a>
                    <% if params[:start_date] %>
                      <a button id='range-btn' class="btn btn-primary nav-link" type="button" href="#custom-range" data-toggle="pill">
                    <% else %>
                      <a button id='range-btn' class="btn btn-default nav-link" type="button" href="#custom-range" data-toggle="pill">
                    <% end %>
                        <%= t('.custom_range') %>
                      </a>
                </div>
              </div>
              <br>
              <div class="tab-content">
              <% if params[:start_date] %>
                <div class="tab-pane" id="summary">
              <% else %>
                <div class="tab-pane active" id="summary">
              <% end %>
                  <%= render "summary" %>
                </div>
                <div class="tab-pane" id="monthly">
                  <%= render "monthly_summary" %>
                </div>
                 <% if params[:start_date] %>
                   <div class="tab-pane active" id="custom-range">
                <% else %>
                  <div class="tab-pane" id="custom-range">
                <% end %>
                   <%= render "hyrax/admin/analytics/date_range_form", redirect_path: hyrax.admin_analytics_work_reports_path %>
                  <%= render "custom_range" %>
                 </div>
              </div>
              <% end %>
            </div>
          </div>
          <p class="text-center"><%= t('.report_generated_on') %> <b><%= Time.zone.today.strftime("%B %d, %Y") %></b></p>

        </div>

      </div>
      <% else %>
        <div class="alert alert-warning" role="alert">
          <%= t('.enable_analytics') %>
        </div>
     <% end %>
    </div>
  </div>
</div>

app/views/hyrax/admin/analytics/work_reports/show.html.erb
<% provide :page_title, "#{t('.title')}" %>

<% provide :page_header do %>
  <h1><span class="fa fa-bar-chart" aria-hidden="true"></span> <%= t('.title') %>
  <%= link_to "#{t('.return_to_btn')}", admin_analytics_work_reports_path, class: "btn btn-primary pull-right" %>
  </h1>
  <br>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <div class="work-reports">
    
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="col-sm-10">
            <h3><%= @document %></h3>
          </div>
          <div class="col-sm-2">
            <%= link_to "#{t('.view_work_btn')}", [main_app, @document], class: "btn btn-default pull-right" %>
          </div>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12 col-md-5">
              <p><%= t('.deposited_by') %> <b><%= @document.depositor %></b> on <b><%= @document.date_uploaded.strftime("%Y-%m-%d") %></b></p>
              <p><%= t('.work_type') %> <b><%= @document.human_readable_type %></b></p>
              <p><%= t('.resource_type') %> <b><%= @document.resource_type.join(", ") %></b></p>
            </div>
            <div class="col-xs-12 col-md-5">
              <p><%= t('.status') %> <b><%= @document.workflow_state %></b></p>
              <p><%= t('.visibility') %> <b><%= @document.visibility %></b></p>
            </div>
          </div>
        </div>
      </div>
          
      <div class="row text-center">
        <div class="nav nav-pills btn-group" role="group">
            <% if params[:start_date] %>
              <a button id='summary-btn' class="btn btn-default nav-link" type="button" href="#summary" data-toggle="pill">
            <% else %>
              <a button id='summary-btn' class="btn btn-primary nav-link" type="button" href="#summary" data-toggle="pill">
            <% end %>
                <%= t('.summary') %>
              </a>
              <a button id='monthly-btn' class="btn btn-default nav-link" type="button" href="#monthly" data-toggle="pill">
                <%= t('.monthly') %>
              </a>
            <% if params[:start_date] %>
              <a button id='range-btn' class="btn btn-primary nav-link" type="button" href="#custom-range" data-toggle="pill">
            <% else %>
              <a button id='range-btn' class="btn btn-default nav-link" type="button" href="#custom-range" data-toggle="pill">
            <% end %>
                <%= t('.custom_range') %>
              </a>
        </div>
      </div>
  <br>
       <div class="tab-content">
          <% if params[:start_date] %>
            <div class="tab-pane" id="summary">
          <% else %>
            <div class="tab-pane active" id="summary">
          <% end %>
              <%= render "summary" %>
            </div>

            <div class="tab-pane" id="monthly">
              <%= render "monthly_summary" %>
            </div>
            
          <% if params[:start_date] %>
            <div class="tab-pane active" id="custom-range">
          <% else %>
            <div class="tab-pane" id="custom-range">
          <% end %>
              <%= render "hyrax/admin/analytics/date_range_form", redirect_path: hyrax.admin_analytics_work_report_path(@document) %>
              <%= render "custom_range" %>
            </div>
        </div>
         
          <% unless @files.nil? %>
            <%= render "work_files" %>
            <%= render "work_counts" %>
         <% end %>
         
    </div>
  </div>
</div>